#!/bin/sh

T='#FFEB3B' # text
R='#607D8B' # Ring
L='#757575' # Keyboard Layout
F='SF Pro Display'

IMAGE=/tmp/lockscreen.png
scrot -o $IMAGE
convert $IMAGE -blur 0x5 -fill black -colorize 25% $IMAGE

i3lock \
    --time-font=$F \
    --date-font=$F \
    --verif-font=$F \
    --verif-size=20 \
    --wrong-font=$F \
    --wrong-size=20\
    --greeter-font=$F \
    --greeter-size=20 \
    --pass-screen-keys \
    --pass-volume-keys \
    --indicator \
    --clock \
    --time-color=$T \
    --time-str="%H:%M" \
    --date-color=$T \
    --date-str="%a, %e %b %Y" \
    --ring-color=$R \
    --layout-color=$L \
    --keylayout=0 \
    -i $IMAGE

# rm $IMAGE
