export FREETYPE_PROPERTIES="truetype:interpreter-version=35"
export EDITOR=nvim
export TERMINAL=kitty

unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)    eval "$(/opt/homebrew/bin/brew shellenv)";;
esac
