export FREETYPE_PROPERTIES="truetype:interpreter-version=35"
export EDITOR=vi
export TERMINAL=kitty
if [ "$XDG_CURRENT_DESKTOP" = "i3" ]; then
    export QT_QPA_PLATFORMTHEME="qt5ct"
    export QT_PLUGIN_PATH=$HOME/.kde4/lib/kde4/plugins/:/usr/lib/kde4/plugins/
fi
